language: java
install: true
addons:
  sonarcloud:
    organization: "p3pp3rf1y-github"
    token: $SONAR_TOKEN

dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: Build
      script:
        - "./gradlew clean"
        - "./gradlew setupCIWorkspace"
        - "./gradlew build"
        - "./gradlew bintrayUpload"
    - stage: Code Quality
      script: ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
